services:
  # Ollama LLM Service
  ollama:
    image: ollama/ollama:latest
    container_name: memory_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    # GPU support disabled - running on CPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    networks:
      - memory_network
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Memory MCP Server
  memory_mcp_server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: memory_mcp_server
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=phi3:mini
      - MEMORY_STORAGE_DIR=/app/brain_memory_store
      - DEBUG_MODE=false
    volumes:
      - ./brain_memory_store:/app/brain_memory_store
      - ./logs:/app/logs
      - brain_database:/app/database
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - memory_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Model Setup Service (runs once to pull models)
  model_setup:
    image: ollama/ollama:latest
    container_name: memory_model_setup
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - memory_network
    environment:
      - OLLAMA_HOST=ollama:11434
    command: >
      sh -c "
        echo 'Pulling models...' &&
        ollama pull llama3.1:8b &&
        ollama pull phi3:mini &&
        echo 'Models ready!'
      "
    restart: "no"

  # Optional: Web UI for direct LLM interaction
  ollama_webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: memory_ollama_webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=your-secret-key-here
    volumes:
      - ollama_webui_data:/app/backend/data
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - memory_network

volumes:
  ollama_data:
    name: memory_ollama_data
  ollama_webui_data:
    name: memory_ollama_webui_data
  brain_database:
    name: memory_brain_database

networks:
  memory_network:
    name: memory_network
    driver: bridge